### ISSUE TITLE
non-resizing plot legend on OSX

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1337] opened 2019-05-20 08:25 UTC
Found in #690 by Paul K.
Plots are hard to read on mac (legends are huge, data is pushed to one side, they keep popping above the fit like whack-a-mole)

This is on OSX on small screen laptops. Matplotlib version = 2.2.2
The same version on Windows behaves properly (legend resized, doesn't go beyond canvas boundary)

**Comment by ajj** [comment] 2019-07-23 10:01
Not just legend text - axis labels don't scale either and are too large, and marker in legend doesn't scale and is too large. Suspect issue with how MacOS reports resolution when there is retina scaling and conflict with what AA_EnableHighDpiScaling in Qt5 is doing.

**Comment by ajj** [comment] 2019-07-23 10:07
![Screenshot 2019-07-23 at 12 07 04](https://user-images.githubusercontent.com/871392/61703703-70988000-ad42-11e9-93c1-e38847f2dc1e.png)


Screenshot from my external monitor running sasview with c789273 - Apple Thunderbolt Display 27" 2560x1440

**Comment by ajj** [comment] 2019-07-23 10:12
<img width="1440" alt="Screenshot 2019-07-23 at 12 08 50" src="https://user-images.githubusercontent.com/871392/61703969-00d6c500-ad43-11e9-9bc7-c0ea320b1fbd.png">

Screenshot from my laptop display with no external display connected running sasview with c789273 (Retina display 2560x1600 real resolution set to default scaling - "looks like 1440x900")

**Comment by ajj** [comment] 2019-07-23 10:23
![Screenshot 2019-07-23 at 12 21 02](https://user-images.githubusercontent.com/871392/61704733-ab9bb300-ad44-11e9-8315-a25f73a4c646.png)


Screenshot from my external display when the laptop is closed. This is more well-behaved. I suspect we need to do something in Qt to determine the active screen and set the scaling accordingly. This does extend the ticket somewhat - it now seems to behave OK with c789273 when only using the laptop screen, but if you attach your laptop to an external display then it is still wonky. Also still need to fix other labels.

**Comment by wpotrzebowski** [comment] 2019-07-24 06:09
@ajj: It seems you run it from the local environment. Does it look the same when you run it from installer, e.g: https://jenkins.esss.dk/sasview-beta/job/SasView-OSX10.13-ghprb/411/? 
We enable NSHighResolutionCapable option for the bundle, so it may behave differently.

**Comment by butlerpd** [comment] 2020-02-05 02:15
As per @wpotrzebowski keeping this for now but moving to 5.0.2 given imminent release of 5.0.1

**Comment by ajj** [comment] 2020-02-18 13:53
> @ajj: It seems you run it from the local environment. Does it look the same when you run it from installer, e.g: https://jenkins.esss.dk/sasview-beta/job/SasView-OSX10.13-ghprb/411/?
> We enable NSHighResolutionCapable option for the bundle, so it may behave differently.

Attached is the screenshot when using 5.0.1 release installer. Still an issue.
<img width="1440" alt="Screenshot 2020-02-18 at 14 46 59" src="https://user-images.githubusercontent.com/871392/74742191-7285db80-525e-11ea-934e-ca02c22fa33f.png">

**Comment by butlerpd** [comment] 2020-03-31 17:02
As per today's conversation am moving this to a 5.0.3 milestone in preparation for a 5.0.2 release. Also am removing the blocker and downgrading to critical since

1. It obviously is not a blocker if we are moving it
2. It has been chipped away at and the problem is not as prevalent as it was originally
3. This is a obviously a much harder nut to crack than it should be since despite a fair amount of work it is still an issue though apparently only in certain cases?

**Comment by butlerpd** [comment] 2020-05-24 23:36
At this point, given all the critical issues, I suspect this is more appropriately at a major than critical level?

**Comment by wpotrzebowski** [comment] 2020-05-25 05:01
Agree

**Comment by krzywon** [comment] 2021-01-12 16:07
@krycket saw a similar issue on Windows using long file names. I'll try to work on this during the hackathon.

![SASViewScreenshot](https://user-images.githubusercontent.com/10947925/104339689-df811000-54c5-11eb-82f8-20380eb53a58.png)

**Comment by ajj** [comment] 2021-02-04 20:04
Still a problem in 5.0.3 with external display on Mac when the laptop screen is also open.

![Screenshot 2021-02-04 at 21 03 23](https://user-images.githubusercontent.com/871392/106948870-8d31b880-672c-11eb-91b4-8143e24d5937.png)

**Comment by pbeaucage** [comment] 2022-10-25 08:20
I have tested this on Mac and can confirm that it fixes the large plot legend.  @krzywon is there anything else we should do before putting this into a PR?

**Closed** 2024-06-06 18:23 UTC
Labels: Defect, Major, Inversion Perspective
