### ISSUE TITLE
5.0 invariant mac not plotting

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1340] opened 2019-05-28 19:53 UTC
Using invariant tutorial in docs (4.2.2) on mac with qt 5.0 release dmg:
* plotting error (see traceback below)
* calculation halts immediately; can't tell if it is computing the desired result since there is no plot.

```
Unhandled Error
Traceback (most recent call last):
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/qt5reactor.py", line 165, in _read
    self.reactor._iterate(fromqt=True)
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/qt5reactor.py", line 271, in _iterate
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py", line 217, in <lambda>
    reactor.callFromThread(lambda: self.plotResult(model))
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py", line 237, in plotResult
    self._manager.filesWidget.plotData(plot_data)
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/MainWindow/DataExplorer.py", line 1040, in plotData
    new_plot.plot(plot_set, transform=transform)
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Plotting/Plotter.py", line 107, in plot
    _, _, xscale, yscale = GuiUtils.xyTransform(self.data, self.data.xtransform, self.data.ytransform)
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Utilities/GuiUtils.py", line 1013, in xyTransform
    data.transformView()
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Plotting/Plottables.py", line 575, in transformView
    self.view.transform(self.x, self.y, self.dx, self.dy)
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Plotting/Plottables.py", line 691, in transform
    raise ValueError(msg)
builtins.ValueError: Plottable.View: Given y and x are not of the same length

0:135: execution error: File some object wasn’t found. (-43)
```

**Comment by wpotrzebowski** [comment] 2019-06-03 06:37
I cannot reproduce this bug. @pkienzle can you please specify which tutorial and which file are you using? The old tutorial that describes Invariant perspective refers to the file circular_test_3.txt that is not a part of current repo. There is circular_test.txt runs without problems (at least in my case).

**Comment by pkienzle** [comment] 2019-06-03 15:40
I can reproduce by first trying corfunc (which is failing similarly to above), then switching to invariant.

If I expand the circular_test.txt data and uncheck the results (High-Q extrapolation, etc.) then send to invariant then the error above disappears.

**Comment by smk78** [comment] 2020-05-01 15:14
Has anyone with a Mac tried this recently to see if it is still an issue?

**Comment by butlerpd** [comment] 2020-05-01 15:21
My cloud mac is sierra I think but I can try on that this weekend.

**Comment by butlerpd** [comment] 2020-05-17 19:18
... I didn't say which weekend of course 😄 

using 5.0.2 I cannot reproduce @pkienzle issue even starting with corfunc. steps taken:
* run SasView
* Load data --> circular_test.txt
* Choose corfunc --> corfunc perspective shows up with empty plots
* Send data to corfunc --> data plots fine on top plot 
* (Optionally click on extrapolate and then transform --> ext. data shows up in top and transform in bottom ... have tried with and without this step)
* Change to invariant --> invariant panel shows up
* Send data to invariant --> data is plotted and invariant is computed

@pkienzle can you give us the exact steps you use? and is this using the 5.0.2 dmg or something built on your own machine?

NOTE: I am surprised that this does not crash the invariant without significantly chopping off the low Q but it doesn't until you try to extrapolate to low Q.

There are however quite a lot of other idiosyncrasies which should probably be reported in other tickets and which I will endeavour to do next.

**Comment by butlerpd** [comment] 2020-08-18 01:07
@pkienzle can we close this ticket?

**Closed** 2020-08-18 16:54 UTC
