### ISSUE TITLE
Issue loading data with 5.0.4 on Windows

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1866] opened 2021-06-03 14:38 UTC
I've been teaching SasView 5.0.4 as SANS course and one of the students had a problem with loading data.
When she tried to open "Load Data" dialog it took ~30 for Windows to come. Drag and dropping worked fine. 
She used latest version of Windows pushed by University update.

**Comment by smk78** [comment] 2021-06-03 20:22
Yes, I've experienced this now and again too. Including with previous versions. See https://github.com/SasView/sasview/issues/1445 Unfortunately I never did nail down the cause.

**Comment by butlerpd** [comment] 2021-06-05 15:45
@wpotrzebowski and/or @smk78, should we try to merge these two tickets? Or do we think they are clearly distinct issues that should have separate tickets?

**Comment by smk78** [comment] 2021-06-06 09:50
I think the reference here will suffice.

**Comment by rozyczko** [comment] 2021-06-21 18:25
Is this happening on the `File Open` dialog show or when a file (files) are selected in the dialog and the actual file load starts?

**Comment by rozyczko** [comment] 2021-06-21 18:38
This might be a manifestation of an old (ancient!) bug in Qt, which so far, hasn't been properly fixed
https://bugreports.qt.io/browse/QTBUG-13182

There are some workarounds listed, which I will try to implement and ask you all to test, if possible.

**Comment by smk78** [comment] 2021-06-22 10:26
> Is this happening on the `File Open` dialog show or when a file (files) are selected in the dialog and the actual file load starts?

As I recall, it was pretty much when the file chooser window appeared; the folder contents part would remain blank for a long time.

**Comment by rozyczko** [comment] 2021-08-05 10:12
The corresponding PR has been merged to `main` meaning we can close this issue?

**Comment by butlerpd** [comment] 2022-01-18 03:16
Not sure why nobody answered you @rozyczko but it seems like this should be closed so will do so now

**Closed by butlerpd** 2022-01-18 03:16 UTC
