### ISSUE TITLE
GSC not drawing the structure

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2734] opened 2024-01-17 20:13 UTC
**Describe the bug**
Testing GSC in 6.0.0a1 [Nightly Build 121](https://github.com/SasView/sasview/actions/runs/7551365880) from `main` on W10/x64.

PDB file loads, but on clicking 'Draw' get the error:

```
2024-01-17 19:35:53,716 : ERROR : sas.qtgui.Perspectives.Fitting.FittingWidget (FittingWidget.py:173) :: Traceback (most recent call last):
  File "sas\qtgui\Calculators\GenericScatteringCalculator.py", line 128, in <lambda>
  File "sas\qtgui\Calculators\GenericScatteringCalculator.py", line 1546, in plot3d
  File "sas\qtgui\Calculators\GenericScatteringCalculator.py", line 1799, in __init__
  File "sas\qtgui\Calculators\GenericScatteringCalculator.py", line 1599, in __init__
  File "sas\qtgui\Plotting\PlotterBase.py", line 30, in __init__
RuntimeError: You can't initialize an PySide6.QtWidgets.QWidget object in class Plotter3D twice!
```

**To Reproduce**
Run SasView
Tools > Generic Scattering Calculator
Load a PDB file as Nuclear Data
Click Draw (not compute)

**Expected behavior**
The structure of the object described by the coordinate data should be drawn.

**Additional context**
This is a bug introduced since 5.0.6

**Comment by butlerpd** [comment] 2024-07-15 01:09
Oops ... #2818 was a duplicate of this and has since been closed as fixed by @rozyczko in PR #2824. So closing this ticket. @smk78, if this is a different bug feel free to reopen but note the difference with #2818 please.

**Closed by butlerpd** 2024-07-15 01:09 UTC
Labels: Defect, Critical, Scattering Calculator Tool
