### ISSUE TITLE
Inoperable close-window action in many widgets

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#2688] opened 2023-12-13 12:30 UTC
**Describe the bug**
Many widgets, mostly modal, don't respond to clicking the exit `X` button in the upper right corner.
This includes:
- complex constraints (as noted in #2685 )
- data operation utility
- most all other calculators

**Expected behavior**
Clicking on `X` should close the widget

**SasView version (please complete the following information):**
 - Version: 6.0.0 (installer only)

**Operating system (please complete the following information):**
 - OS: Win10

**Additional context**
Hitting Esc closes the offending widget.

Works fine in developer build (meaning it'll be fun to debug)

**Comment by gonzalezma** [comment] 2023-12-13 13:02
Really? For me, also in my dev build the x-button is disabled. If I can provide you more info or you can guide me on what to look at/test, just tell me.
Good hint about using Esc to close the window. But should we have in any case (even if the issue is solved) a close button, like for almost all other windows?

**Comment by krzywon** [comment] 2023-12-13 15:09
I did a quick test and I think the line `self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowContextHelpButtonHint)` in modal windows is the culprit. Commenting out the entire line or removing `& ~QtCore.Qt.WindowContextHelpButtonHint` reinstated the window close button. I'm not sure why this works, or what the original intent of the flags so I haven't committed anything.

**Comment by rozyczko** [comment] 2023-12-14 09:35
> I did a quick test and I think the line `self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowContextHelpButtonHint)` in modal windows is the culprit. Commenting out the entire line or removing `& ~QtCore.Qt.WindowContextHelpButtonHint` reinstated the window close button. I'm not sure why this works, or what the original intent of the flags so I haven't committed anything.

Bizarre. I did exactly that in my bugfix branch `2688-inoperable-close-window-action` and it didn't work for me...

**Comment by rozyczko** [comment] 2023-12-16 20:39
`CI #1466` failed on a Mac and succeeded on Windows. This had the context help flag removed in the Data Operation Tool. The Windows installer showed no behaviour difference in closing the widget.
The next build `CI #1477` passed on all platforms, despite the source differing by just one more deletion of the Windows flag.
This worked fine for both Data Operation and Density tools...
Most likely versioning of some dependency played a role?

**Comment by rozyczko** [comment] 2023-12-16 20:41
Anyway, deletion of the flags is solving the problem and doesn't leave the question mark icon enabled, so removed it.

**Comment by gonzalezma** [comment] 2024-01-16 22:40
Solved by PR #2690.

**Closed by gonzalezma** 2024-01-16 22:40 UTC
