### ISSUE TITLE
Append To combo box only has one graph option for Theory data

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2118] opened 2022-07-08 18:29 UTC
**Describe the bug**
When you have multiple datasets in the Data Explorer you have the option to select one or more and Create [a] New graph, _or_ to Append [them] To an existing graph.

It seems that the second of these two actions is only available to Data data and not Theory data.

**To Reproduce**
1. Run SasView
2. Create a FitPage and select any model. Calculate the model and then Compute/Plot the calculation.
3. Now create a second FitPage and repeat the process.

This creates a couple of Theory datasets and a graph of each calculation.
![image](https://user-images.githubusercontent.com/10938679/178048597-b23e1756-04c6-4b1c-b4f7-352cf8967d73.png)
![image](https://user-images.githubusercontent.com/10938679/178048122-9ca1c19b-ea67-4b8b-b3f1-176dc24d667e.png)
 
4. Now select one or other of the Theory datasets and try Append To the graph with the other dataset (ie, to put both datasets on the same graph).

There is only one graph option in the combo box.
![image](https://user-images.githubusercontent.com/10938679/178048550-26b00ba6-e3b2-48a4-836e-8477f2713b24.png)

**Expected behavior**
All of the generated graphs should be available in the combo box.

**SasView version (please complete the following information):**
 - Version: release 5.0.5, but affects all 5.x.

**Operating system (please complete the following information):**
 - OS: W10/x64

**Additional context**
The expected behaviour is available in 4.2.2. This issue was introduced in 5.x.

**Comment by rozyczko** [comment] 2022-07-11 07:55
Just did this with 5.0.5 and got the second theory plot correctly appended.
It would be good to see what is the different between what we both did

![Untitled](https://user-images.githubusercontent.com/8266281/178215886-d82d35e6-9104-4df7-bffb-442d89e546e5.png)

**Comment by smk78** [comment] 2022-08-08 09:51
@rozyczko , sorry for the delay in picking this up. But did you do that in the release version or your dev version?

I've just uninstalled release 5.0.5, re-downloaded & re-installed it, and I can re-create this issue at will.

**Comment by butlerpd** [comment] 2022-08-08 15:01
Looking at the examples ...I'm guessing that @rozyczko tried to append M2 to graph 1? That does work for me too. The problem is that if you cannot append M1 to Graph 2. In fact you cannot append anything to anything except graph 1. At least in my test of 5.0.5. Not sure if that helps?

**Comment by smk78** [comment] 2022-08-08 18:30
Yes, that's my point (arguably expressed better)! You can create as many plots as you like but you can only append a Theory to Graph1 in 5.x. Thanks, @butlerpd .

**Comment by rozyczko** [comment] 2022-08-08 19:07
Ah! yes, I can reproduce the problem now. So the bug is in the content of the plot combobox when theory plots are generated.
Thanks for pointing this out, @butlerpd

**Comment by rozyczko** [comment] 2022-10-27 12:52
Addressed by https://github.com/SasView/sasview/pull/2298

**Comment by lucas-wilkins** [comment] 2022-11-08 14:23
This appears to have been merged. Just forgot to close the issue.

**Closed by lucas-wilkins** 2022-11-08 14:23 UTC
Labels: Defect, For Feature Parity, Main GUI Window
