### ISSUE TITLE
5.0 turn off or remove constraint ?

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1589] opened 2020-06-12 16:29 UTC
following the example in  https://github.com/SasView/sasview/issues/1588

If I have a constraint for  M3.sld_shell = M2.sld_shell   but turn off M2.sld_shell and set it to a new value,  then M3.sld_shell shows still as constrained, but at its earlier value.

Logically the user (OK myself) would expect the constraint to still be working. However due to the way sasview treats constraints this may be difficult to achieve?  Though it would only take a single pass through the constraints at the start of "fit" or "compute". Automatically removing the constraint would be irritating, but "safer" if this is not possible.

(OK also I would still have  also liked to be able to set constraints in the first place between any parameter regardless of whether they were adjusting or not, but I was out voted.)

**Comment by gonzalezma** [comment] 2020-06-13 18:18
As far as I can see, the constraint works as expected. Or perhaps I did not fully understand your problem?

It is true that if one changes the value of the parameter (e.g. M2.sld_shell), the constrained parameter (M3.sld_shell) is not automatically updated, but as soon as one does Fit in the constrained and simultaneous fit page, the constraint is applied and one gets that M3.sld_shell has the same value as M2.sld_shell.

It could be nice that once that a constraint is defined, any change in a parameter is automatically passed on the other parameters tied to it, but I'm afraid that this is not trivial as it involves interactions between several pages in the GUI (certainly it is too complex for me, but perhaps Nico or Piotr can comment on this).

For your last point, this is not fixed on the stone so it could be reconsidered. But what is the main benefit that you see on defining constraints for parameters that are not going to be adjusted?

**Comment by butlerpd** [comment] 2020-06-14 16:19
sorry if I missed an earlier conversation but can you elaborate on the comment
> (OK also I would still have also liked to be able to set constraints in the first place between any parameter regardless of whether they were adjusting or not, but I was out voted.)

Like Miguel I would be interested in the use case to better understand what you are suggesting

Are you asking for constraints between 2 non adjusting parameters - e.g. M1.radius=M2.radius=M3.radius or M1.radius=2*M1.length etc where **ALL** of these are non-adjustable? If so what is the purpose/use case? So if you want to manually change the parameter it then automatically updates the other parameters? Something else?

Or are you talking about being able to constrain an adjustable parameter to some function of a non adjustable parameter? If so what is the use case? For example M1.length=2*M1.radius where M1.length is variable but M1.radius is fixed.

Or something altogether different?

**Comment by m2cci-NMZ** [comment] 2020-06-14 18:00
The constraints are only used as information for fit, so you will not see the value of the slave parameter changing when you change the master parameter. The problem is that the constraint is attached to the slave parameter, which means that the master parameter has no idea of which parameter it is attached to. To achieve this behaviour (slave parameter changing when the master parameter is changed), we would need to parse all the constraints across all fit pages every time a parameter is changed, check if it is involved in a constraint and change the value of the slave parameter accordingly, which is indeed not trivial as @gonzalezma pointed out :-), but still doable.

**Comment by RichardHeenan** [comment] 2020-06-15 09:58
OK, sorry!  My original report above was _not_ correct, once you hit "fit" in the "Const. Simul Fit" tab the constraint is working through from the now fixed value of the master parameter. As has been said, waiting for the user to do this is the best we can offer, without some complex code to check for changes.

The default typical workflow is to set up several FitPages, so they work as individual fits, then find the constraints tab and use the "all" button to link all _fitting_ parameters (wherever there is a name match) but _not_ the fixed ones. This is likely to be useful for example when dealing with 2 or 3 different sample-detector distances.  
Sometimes it is quicker, e.g. with a long series of contrasts, to link absolutely everything, including the fixed parameters, then to delete a few that are not needed.
Perhaps we could have an "all in fit" and an "all" (really all) button on the quick constraints set up?

It is often the case that a fixed parameter is in a constraint, why do I have to go through all the model tabs to turn them all "on" to get them to appear in the drop-down parameter choosers when setting up constraints individually? Can we have them all there please, as we did until recently ( apart of course from ones already constrained, as sasview does not allow nested constraints).

Logically the constraints tell me what I know about the system as a whole, I might want to tie say all the sld_shell, then decide later whether I want to try to fit the common value. After a trial fit it might go to some unphysical value, so then I fix it and adjust it back manually to something sensible. (I could of course set the max & min value range to help do this.)

**Additionally**, now when I hit fit on an individual FitPage, it comes up with a box asking whether to remove constraints that rely on other FitPages or to cancel fitting. It does not need to remove the constraints, just to "uncheck" them please in the constraints tab.

**Comment by m2cci-NMZ** [comment] 2020-06-16 14:30
If I understand correctly, what would be usefull would be an option to tie **all** parameters with the same name together. For example, in a contrast variation experiment with a spherical model, tying all radius to the same value. This could be achieved by having an All option in the most left drop-down menu  in the `ComplexConstraint` widget, e.g if we have three fit pages and selecting All:radius = M3.radius would then create 2 constraints M1:radius = M3.radius and M2:radius = M3.radius. I guess this could be simpler than tying all parameters together and then removing unwanted constraints manually
Lionel was also suggesting this type of feature.

**Comment by RichardHeenan** [comment] 2020-06-19 10:35
Your suggestion of an All:radius = might be useful, though we would have to quibble over whether the first or the last selected model is the master one.

**Comment by RichardHeenan** [comment] 2020-06-19 10:55
Shall I put in a separate issue for the : **Additionally,** now when I hit fit on an individual FitPage, it comes up with a box asking whether to remove constraints that rely on other FitPages or to cancel fitting. It does not need to remove the constraints, just to "uncheck" them please in the constraints tab.

**Comment by m2cci-NMZ** [comment] 2020-06-19 11:06
> Your suggestion of an All:radius = might be useful, though we would have to quibble over whether the first or the last selected model is the master one.

I was thinking of putting the right side parameter as master to follow the logic

> Shall I put in a separate issue for the : **Additionally,** now when I hit fit on an individual FitPage, it comes up with a box asking whether to remove constraints that rely on other FitPages or to cancel fitting. It does not need to remove the constraints, just to "uncheck" them please in the constraints tab.

I guess having a separate ticket is not necessary, could be fixed in a unique PR :-)

**Comment by RichardHeenan** [comment] 2020-08-10 15:21
Have added a new issue #1654 for the "remove constraints" issue. I think the consensus seem to be that constrained parameters should be checked "on" and stay "on" as well as turning into blue italics.

This only leaves the idea of having an additional option for  "constrain all" that is "really all" rather than "all that are currently turned on"

**Comment by pkienzle** [comment] 2020-08-10 16:43
Just to be clear, "constrain all" should be an action button rather than a toggle state. That is, you will want to constrain all and then turn off constraints for whatever parameters are actually varying amongst the datasets.

Regarding `background`, should it default to constrained or unconstrained when clicking "constrain all"? That is, are backgrounds usually independent between the measurements, or usually the same?

**Comment by RichardHeenan** [comment] 2020-08-11 10:10
re flat backgrounds (usually incoherent and/or inelastic for SANS) - that may be same between constrained Fitpages e.g. for two or three different sample-detector distances, or they may be different e.g. for different D/H ratio contrasts. So if there is a "constrain really all" action button, then we may as well include the scales and backgrounds, then let the user disable some accordingly.

**Comment by m2cci-NMZ** [comment] 2020-09-07 12:08
I'm also restoring constraint edition in the constraint tab. The user will be able to change the **expression** and the constrained **parameter**. Changing the **expression** is straightforward, but what should I do with the **parameter**? Should the previous constraint remain and a new one added or should it be replaced e.g. if we have: 
`M1:radius = M1.length`
and the user edits the constraint by changing `M1:radius` to `M1:sld` should it be:
`M1:radius = M1.length` and `M1.sld = M1.length` (addition of new constraint)
or
`M1:sld = M1.length` (replacement of constraint)

**Comment by RichardHeenan** [comment] 2020-09-08 15:02
> I'm also restoring constraint edition in the constraint tab. The user will be able to change the expression and the constrained parameter. Changing the expression is straightforward, but what should I do with the parameter? Should the previous constraint remain and a new one added or should it be replaced e.g. if we have:
> M1:radius = M1.length
> and the user edits the constraint by changing M1:radius to M1:sld should it be:
> M1:radius = M1.length and M1.sld = M1.length (addition of new constraint)
> or
> M1:sld = M1.length (replacement of constraint)
> Replacement seems more intuitive but the other option is also doable

I would do whatever is simplest and most robust, which ever way someone might complain, but they should not be so fussy.

**Closed** 2020-10-27 12:17 UTC
Labels: defect
