### ISSUE TITLE
cross check dll/opencl/python polydispersity and orientation results (Trac #954)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1030] opened 2019-03-30 08:51 UTC
Implement 1D/2D versions symmetric and asymmetric particles in pure python so that we can cross check the polydispersity calculations in the three different implementations of the polydispersity loop.  

Ellipsoid and triaxial ellipsoid for example.

Migrated from http://trac.sasview.org/ticket/954
```json
{
    "status": "closed",
    "changetime": "2017-05-02T11:30:53",
    "_ts": "2017-05-02 11:30:53.546175+00:00",
    "description": "Implement 1D/2D versions symmetric and asymmetric particles in pure python so that we can cross check the polydispersity calculations in the three different implementations of the polydispersity loop.  \n\nEllipsoid and triaxial ellipsoid for example.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-04-11T09:42:47",
    "component": "SasView",
    "summary": "cross check dll/opencl/python polydispersity and orientation results",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment] 2019-03-30 10:12
Trac update at `2017/05/02 11:30:53`: 
* **richardh** commented:

 duplicate of #1029


* **richardh** changed resolution from "" to "duplicate"
* **richardh** changed status from "new" to "closed"

**Closed by RichardHeenan** 2019-03-30 10:12 UTC
Labels: Migrated from Trac, SasView Bug Fixing, defect, major
