### ISSUE TITLE
Window problems when using maximised perspectives

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2449] opened 2023-03-03 13:14 UTC
**Describe the bug**
Windows misbehave when a perspective is maximised and swapped, a new blank window appears

**To Reproduce**
1. Start SasView
2. Maximise fitting perspective
3. Use send to send data to another perspective, e.g. Corfunc
4. A new blank window will appear

**Expected behavior**
Swap between perspectives

**SasView version (please complete the following information):**
 - main

**Operating system (please complete the following information):**
 - OS: Windows 10

**Comment by lucas-wilkins** [comment] 2023-03-03 13:14
@rozyczko This seems like your kind of thing ;)

**Comment by krzywon** [comment] 2023-03-03 20:58
Similar behavior happens when the active perspective is minimized, a minimized window is created. I have a hacky patch in https://github.com/SasView/sasview/tree/2449-perspective-change-extra-window, but would prefer to understand the root cause of the issue before submitting a pull request.

**Comment by lucas-wilkins** [comment] 2023-03-04 12:08
@krzywon I don't know why we have this switching behaviour in the first place to be honest. It would be more natural just to be able to open and close each perspective.

**Comment by krzywon** [comment] 2023-03-06 14:25
@lucas-wilkins This switching was added in v5.0.4. Closing the perspective destroys it and any progress made on it. This was counter to the behavior in v4.x and users were complaining they would create a complex fit, run that fit, then switch to another perspective to perform other analyses, only to find the original fit is now gone and unrestorable.

Two other ways I can think we handle this if we want to go the close/open route:
1. Allow any number of perspectives to be open at a time. This creates more windows, which is something we want to reduce as it is. (1a: Create a tabbed perspective window that houses each perspective under a different tab.)
2. Serialize the perspective when it closes and deserialize it when it reopens. There is a performance hit when deserializing, and there are plenty of bugs related save/load.

**Comment by rozyczko** [comment] 2023-03-07 08:53
> @rozyczko This seems like your kind of thing ;)

Not chipping in, since annoyingly, I can't reproduce this issue (Win10, local build or installer build)

**Comment by rozyczko** [comment] 2023-03-17 14:08
I can reproduce it in `main` and I fixed the issue, without having to manually resize the windows.

**Closed** 2023-03-23 17:11 UTC
Labels: Defect, Main GUI Window
