### ISSUE TITLE
Clicking on a graph in the Windows menu throws an error

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3018] opened 2024-08-15 00:44 UTC
**Describe the bug**
Clicking on a plot in the Window menu no longer brings the plot into focus but throws the following error
```python
00:58:13 - ERROR: TypeError: GuiManager.addPlotItemsInWindowsMenu..() missing 1 required positional argument: 'chk'
```
**To Reproduce**
1. Makes some fits (NOTE: that only subplots currently will allow a graph to show up in the Windows menu see issue #3017)
2. Make some plots that include at least one subplot data set in each plot
3. Go to the Window menu and click on one of the graph windows
4. Nothing happens except that the error is thrown.

**Expected behavior**
No error is thrown and the selected plot is made the focus

**SasView version (please complete the following information):**
 - Version: 6.0.0b2

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
Identified during the NIST CNR summer school

**Comment by krzywon** [comment] 2024-08-15 13:03
This is a duplicate of #2837 and has already been fixed in the release branch by #3002.

**Closed by krzywon** 2024-08-15 13:03 UTC
Labels: Major, SasView 6.0.0
