### ISSUE TITLE
Cleanup sas.sasview IV - The Linux Chronicles 

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2155] opened 2022-08-17 14:05 UTC
Within `installers` there are various files relating to linux, including many `.spec` files (which are for creating RPM packages).

I don't know what to do with run_sasview.sh and set_sasview_qt5_path.sh - are they used? (they could be one file, at least)

The spec files are out of date. There's a lot to maintain and test there. The only one that seems to be used is `sasview.spec`.

What should be done here? @krzywon @pkienzle @wpotrzebowski @rozyczko @butlerpd

**Comment by rozyczko** [comment] 2022-08-17 14:40
Currently, after moving to github, only the main file `sasview.spec` is being maintained and used. The other spec files were necessary for old, ESS-based Jenkins builds. They can be safely deleted.
`run_sasview.sh` was a file to start SV on older versions of CentOS. IT would be good to check if the current linux installers can be run on CentOS and if so, delete these two shell scripts as well

**Comment by lucas-wilkins** [comment] 2022-08-17 16:19
@rozyczko I can only see them in jenkins files. Perhaps the jenkins files need to go too, in fact, I see a lot of stuff in `build_tools` that has dubious value.

> older versions of CentOS.

Is there any other kind ;)

Thanks.

**Comment by rozyczko** [comment] 2022-08-17 16:44
The jenkins files are ripe for removal. The main `sasview.spec` should be kept or maybe moved to a more appropriate location if `build_tools` proves empty after your cleanup

**Comment by llimeht** [comment] 2022-08-18 12:38
> Within `installers` there are various files relating to linux, including many `.spec` files (which are for creating RPM packages).

For maximum confusion, these are actually pyinstaller config not rpm config files, but yes, only one is actively maintained of late.

For context, removing lots of version pinning on old versions of dependencies was key to being able to unify the spec files, and getting pyinstaller working as intended.

**Closed** 2022-08-19 13:55 UTC
Labels: Infrastructure, Housekeeping
