### ISSUE TITLE
Edit slicer parameters broken in 5.0

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1350] opened 2019-06-10 22:40 UTC
There are a series of problems with the various slicers.

First the this panel is very simplistic and does not contain any of the batch, fitting, log/linear etc features added at code camp VI held in Grenoble in April 2017.  

Also it seems that he big ugly boxe "handles" may be gratuitous in Qt where it seems you can grab the line and move it?

More importantly however:

1. The few parameters available in the Edit Slicer Parameter panel seem editable and do change until one hits return then they revert to their original value.  No changes is ever made.  Note that dragging the box cursors does change the panel values
2. The parameters that are presented for the Box Sum however **DO** work as expected
3. the Sector average lines do not move when grabbed until the mouse is released.  This means one cannot see what the lines are going to include till after releasing the mouse button.  The box and annular averages do move with the cursor while holding the button.

**Comment by butlerpd** [comment] 2019-06-10 22:51
This used the release version on windows 7.  However, while the first two times the programs was started and tested it exhibited problem of point 2 with an error apparently of
` ERROR: SasView threw exception: validate() takes 1 positional argument but 3 were given`
on the 3rd start up of the program to test, point 2 is not a problem nor is it throwing an error (point 3 remains true).  Suspect that in the first two cases the first steps tested caused the error and that once the error was thrown the program was locked into the error no matter what slicer was being used.  Does need more testing at this point.

**Comment by butlerpd** [comment] 2019-06-10 23:07
More testing and the error is real.  On the fourth go the problem is back (same error).  Moreover it is clear there is a lot of crosstalk which is probably the origin of the problem.  First 2D date sent to new plot and do a box average edit slicer does not work. Second 2D data set sent to "create new plot" and not only do you get the new plot but also a second copy of the 1D slicer plot ... but of the first data set. Then do another box average on the new data.  Edit parameter also does not work.

Now clear all slicers then remove all plots.  Now send a third 2D data set to "Create new plot" and the 2D data is plotted along with one 1D plot containing 2 curves: the 1D box averages for the previous two data sets run.

**Comment by rozyczko** [comment] 2019-06-11 09:32
Issue 1. from the first report - Cannot reproduce it - modifying values in the Edit Slicer Parameters box causes corresponding changes in the plot. Closing the Edit Slicer Parameters box does not cause the parameters to revert to original values. Can you please describe steps to reproduce this behaviour?

Issue 3 - bug indeed. will be fixed in 5.0.1

Second report - `validate()` errors - can't reproduce this locally but will have a look at the code to see if this method gets called differently from places.

Third report - Could you please describe the steps to reproduce? Following your current description and don't see the bahaviour.

**Comment by rozyczko** [comment] 2019-08-08 08:09
ready for review in ESS_GUI_plotting_issues

**Closed** 2019-09-11 07:36 UTC
