### ISSUE TITLE
SasView 6.0.0 fails to launch

### ISSUE THREAD

**Issue by jack-rooks** [SasView/sasview#2729] opened 2024-01-17 18:35 UTC
**Describe the bug**
Using the run.py file in sasview for the latest 6.0.0 branch briefly shows the sasview splash window then provides the following error:
```
13:26:39 - OpenGL.acceleratesupport - DEBUG - OpenGL_accelerate module loaded
13:26:39 - OpenGL.arrays.arraydatatype - DEBUG - Using accelerated ArrayDatatype
Traceback (most recent call last):
  File "C:\Users\Jack\GitRepos\sasview\run.py", line 94, in <module>
    sys.exit(sas.cli.main(logging="development"))
  File "C:\Users\Jack\GitRepos\sasview\src\sas\cli.py", line 161, in main
    run_sasview()
  File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\MainWindow\MainWindow.py", line 106, in run_sasview
    mainwindow = MainSasViewWindow()
  File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\MainWindow\MainWindow.py", line 42, in __init__
    from .GuiManager import GuiManager
  File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\MainWindow\GuiManager.py", line 37, in <module>
    from sas.qtgui.Utilities.DocViewWidget import DocViewWindow
  File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\Utilities\DocViewWidget.py", line 13, in <module>
    from sas.sascalc.doc_regen.makedocumentation import make_documentation, HELP_DIRECTORY_LOCATION, MAIN_PY_SRC, MAIN_DOC_SRC
  File "C:\Users\Jack\GitRepos\sasview\src\sas\sascalc\doc_regen\makedocumentation.py", line 65, in <module>
    def get_py(directory: Union[Path, os.path, str]) -> list[Union[Path, os.path, str]]:
  File "C:\Users\Jack\Anaconda3\envs\sasview_dev\lib\typing.py", line 277, in inner
    return func(*args, **kwds)
  File "C:\Users\Jack\Anaconda3\envs\sasview_dev\lib\typing.py", line 354, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\Jack\Anaconda3\envs\sasview_dev\lib\typing.py", line 466, in Union
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Users\Jack\Anaconda3\envs\sasview_dev\lib\typing.py", line 466, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Users\Jack\Anaconda3\envs\sasview_dev\lib\typing.py", line 166, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Union[arg, ...]: each arg must be a type. Got <module 'ntpath' from 'C:\\Users\\Jack\\Anaconda3\\envs\\sasview_dev\\lib\\ntpath.py'>.

Process finished with exit code 1
```

**To Reproduce**
1. Checkout `release_6.0.0`
2. Run the `run.py` file
3. See error

**Expected behavior**
Sasview will launch

**SasView version (please complete the following information):**
 - Version: 6.0.0a

**Operating system (please complete the following information):**
 - OS: Windows 10 Version 10.0.19045 Build 19045

**Additional context**
Using the master branch of sasdata and sasmodels. Running succeeds when using the master branch of sasview

**Comment by rozyczko** [comment] 2024-01-17 19:17
duplicate of https://github.com/SasView/sasview/issues/2727

**Closed** 2024-01-17 19:32 UTC
Labels: Defect, Critical, Code Camp 2023
