### ISSUE TITLE
Unticking No OpenCL on Mac fixes problem with no model fit (Trac #1000)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1071] opened 2019-03-30 08:52 UTC
Reported by user Simon Martin using Mac Pro with Mac OS 10.12.6:

Using !SasView 4.1 and later (including 4.1.2) no model (theory) calculation was being generated.

smk78 suspected an OpenCL issue and asked user to TICK the No OpenCL box in Fitting > OpenCL Options.

However, user reported that No OpenCL was ALREADY TICKED and that UNTICKING it actually solved the problem! This is clearly unexpected behaviour.

This issue may be related to #1066 ?

Migrated from http://trac.sasview.org/ticket/1000
```json
{
    "status": "assigned",
    "changetime": "2018-10-16T14:17:14",
    "_ts": "2018-10-16 14:17:14.034535+00:00",
    "description": "Reported by user Simon Martin using Mac Pro with Mac OS 10.12.6:\n\nUsing !SasView 4.1 and later (including 4.1.2) no model (theory) calculation was being generated.\n\nsmk78 suspected an OpenCL issue and asked user to TICK the No OpenCL box in Fitting > OpenCL Options.\n\nHowever, user reported that No OpenCL was ALREADY TICKED and that UNTICKING it actually solved the problem! This is clearly unexpected behaviour.\n\nThis issue may be related to #995 ?\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-09-21T16:32:18",
    "component": "SasView",
    "summary": "Unticking No OpenCL on Mac fixes problem with no model fit",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by butlerpd** [comment] 2019-03-30 10:15
Trac update at `2017/12/12 14:45:30`: 
* **butler** changed owner from "" to "awashington"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment] 2019-03-30 10:15
Trac update at `2017/12/12 14:46:29`: **butler** changed owner from "awashington" to "wojciech"

**Comment by wpotrzebowski** [comment] 2019-03-30 10:15
Trac update at `2017/12/14 12:47:18`: **wojciech** commented:

Unticking "No OpenCL" (leaving all boxes empty) resets samodels defaults and most likely falls back to OpenCL compilation. This means that user could have a problem with standard c compiler. My assumption is that user didn't install Xcode Command Line Tools when was asked for it when ran SasView for the first time. 

We assume that mac compiler is always available and I guess can continue with this approach. Therefore I am not sure if underlying problem is in "OpenCL Options"  

@smk78: can you please check with the user if he/she has c compiler installed?

**Comment by smk78** [comment] 2019-03-30 10:15
Trac update at `2017/12/15 11:08:09`: **smk78** commented:

@wojciech: The user concerned is that same one who now has a different problem with a reflectivity plugin they've written (that I circulated the other day). Given that model had a .c module that is falling over on compile I assume they have a c compiler!

@smk78: You are right, they probably have a c compiler installed. More specific question is what version and if it is native or custom build compiler. It may be that for some reason !SasView fails on 10.13 (I am not sure if anyone tested it).

**Comment by smk78** [comment] 2019-03-30 10:15
Trac update at `2017/12/15 11:09:33`: **smk78** commented:

User reports:

I do have Xcode, and the Command Line Tools as well.

gcc -v produces:

Configured with: --prefix=/!Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
!InstalledDir: !/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by wpotrzebowski** [comment] 2019-03-30 10:15
Trac update at `2018/01/11 08:23:22`: 
* **wojciech** changed _comment0 from:

> I've managed to reproduce the behaviour on the fresh OSX 10.12 but I think SasView behaves as expected. 
> 
> 1. When you run sasview for the first time (on the fresh system) it asks for installing xcdoe command line tools. When you click on "Not Now" button it will skip installation but will raise a proper error when you try to compile with c compiler "No OpenCL" ticked
> 
> 2. When you then untick "No Opencl" sasview will fall back to GPU compilations and then the models get compiled. 
> 
> 3. But still when you tick "No OpenCl" again and try to compile with c compiler again it raises proper error again and pops up Xcode installation dialog. 
> 
> So it seems that Xcode is persitant enough to force c compiler installation. 
> 
> This doesn't exactly adress problem Simon Martin mention (as he had Xcode installed) but I expect it is something along these lines.

to:

> 1515659782979081


* **wojciech** commented:

I've managed to reproduce the behaviour on the fresh OSX 10.12 but I think SasView behaves as expected. 

1. When you run sasview for the first time (on the fresh system) it asks for installing xcdoe command line tools. [[Image(Screen Shot 2018-01-11 at 09.03.16.png​)]] When you click on "Not Now" button it will skip installation but will raise a proper error when you try to compile with c compiler - "No OpenCl" ticked [[Image( Screen Shot 2018-01-11 at 09.04.07.png)]]

2. When you then untick "No Opencl" sasview will fall back to GPU compilations and then the models get compiled with OpenCl. 

3. But still when you tick "No OpenCl" again and try to compile with c compiler again it raises proper error again and pops up Xcode installation dialog.[[Image(Screen Shot 2018-01-11 at 09.27.54.png)]] 

So it seems that Xcode is persitant enough to force c compiler installation. 

This doesn't exactly adress problem Simon Martin mention (as he had Xcode installed) but I expect it is something along these lines.

**Comment by wpotrzebowski** [comment] 2019-03-30 10:15
Trac update at `2018/01/11 08:25:38`: **wojciech** changed attachment from "" to "Screen Shot 2018-01-11 at 09.04.07.png"

**Comment by wpotrzebowski** [comment] 2019-03-30 10:15
Trac update at `2018/01/11 08:25:49`: **wojciech** changed attachment from "" to "Screen Shot 2018-01-11 at 09.03.16.png"

**Comment by wpotrzebowski** [comment] 2019-03-30 10:15
Trac update at `2018/01/11 08:32:31`: **wojciech** changed attachment from "" to "Screen Shot 2018-01-11 at 09.27.54.png"

**Comment by butlerpd** [comment] 2019-03-30 10:15
Trac update at `2018/01/23 14:30:42`: **butler** changed priority from "critical" to "major"

**Comment by butlerpd** [comment] 2019-03-30 10:15
Trac update at `2018/02/13 02:53:20`: 
* **butler** commented:

Since this seems to be very specific to the way this user's computer is set up and cannot be reproduced. downgrading to minor and moving to 4.3.


* **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by smk78** [comment] 2019-03-30 10:15
Trac update at `2018/10/16 14:16:14`: 
* **smk78** changed attachment from "" to "IMG_1821.jpg"
* **smk78** commented:

Different command line tools warning encountered

**Comment by smk78** [comment] 2019-03-30 10:15
Trac update at `2018/10/16 14:17:14`: **smk78** commented:

Encountered this different command line tools warning whilst help install 4.2.0 release on a Users Mac.

**Comment by butlerpd** [comment] 2020-04-26 17:52
@smk78 (and @wpotrzebowski ) since this user complaint is quite old and we continue to have opencl issues but have mostly found work arounds for now, can I assume this ticket can be closed? If not is is appropriate to move to 5.1 or is this specific to 4.x? It the latter then I suggest we move it to the graveyard of known issues we cannot fix in the 4 series (unless some clever OpenCL person has a burning itch to do so:-)

**Comment by smk78** [comment] 2020-04-27 12:04
Since I am not using OpenCL in general, nor have a Mac, I cannot comment.

**Comment by wpotrzebowski** [comment] 2020-04-30 04:57
It cannot reproduce it with 5.0.2, so I don't think we have to move it to 5.1. And for 4.x I assume this still may be an issue but requires more time to explore it.

**Comment by butlerpd** [comment] 2020-04-30 13:28
Ok ... Are you arguing to try to keep this open for 4.3 the? I guess we can leave it for now, but I really don't see any work happening on this any time soon?  I do note that doing statistics on our download page, about 80% of downloads (going back to 4.1.2 I think I went) are for windows so that would be another reason not to put effort on this for 4.x? Plus 4.x has always been less friendly for macs so maybe we can push them to 5.x faster? we'll leave it in 4.3 for now but my vote is to move to the graveyard.

**Comment by lucas-wilkins** [comment] 2022-10-30 21:07
Closing as "wont do"

**Closed by lucas-wilkins** 2022-10-30 21:07 UTC
Labels: Migrated from Trac, Defect, Major, SasView Bug Fixing
