### ISSUE TITLE
control order in which fit parameters appear in gui (Trac #348)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#483] opened 2019-03-30 08:40 UTC
Suspect that the current “almost alphabetical” order for most but not all models is an “accident” due to python dictionaries.

\models\c_extension\python_wrapper\WrapperGenerator.py, ~line 328, routine write_c_wrapper produces a python type dictionary  by:

 for par in self.params: param_str += "        
PyDict_SetItemString(self->params,\"%s\",Py_BuildValue(\"d\",%10.12f));\n" % \      (par, self.params[par])

The main parameter dictionary may then have the polydispersity parameters added on to it. Alas python dictionaries are assembled in random order due to use of hash tables.

When a model is loaded “param_list” is acquired via 

\sas\models\BaseModel.py, ~line 125.

    def getParamList(self):
        param_list = self.params.keys()
        return param_list

[Note that many other places have similar routines for other parts of sasview.]

Would it be possible to use an ordered dictionary, in order to keep parameter in a particular order, such as the order in which the default values appear.

Paul Kinsell warns that there will be consequences for the way he passes parameters to fitting routines.

Migrated from http://trac.sasview.org/ticket/348
```json
{
    "status": "closed",
    "changetime": "2016-03-20T11:46:32",
    "_ts": "2016-03-20 11:46:32.824365+00:00",
    "description": "\nSuspect that the current \u201calmost alphabetical\u201d order for most but not all models is an \u201caccident\u201d due to python dictionaries.\n\n\\models\\c_extension\\python_wrapper\\WrapperGenerator.py, ~line 328, routine write_c_wrapper produces a python type dictionary  by:\n\n for par in self.params: param_str += \"        \nPyDict_SetItemString(self->params,\\\"%s\\\",Py_BuildValue(\\\"d\\\",%10.12f));\\n\" % \\      (par, self.params[par])\n\nThe main parameter dictionary may then have the polydispersity parameters added on to it. Alas python dictionaries are assembled in random order due to use of hash tables.\n\nWhen a model is loaded \u201cparam_list\u201d is acquired via \n\n\\sas\\models\\BaseModel.py, ~line 125.\n\n    def getParamList(self):\n        param_list = self.params.keys()\n        return param_list\n\n[Note that many other places have similar routines for other parts of sasview.]\n\nWould it be possible to use an ordered dictionary, in order to keep parameter in a particular order, such as the order in which the default values appear.\n\nPaul Kinsell warns that there will be consequences for the way he passes parameters to fitting routines.\n",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2015-02-18T15:33:05",
    "component": "SasView",
    "summary": "control order in which fit parameters appear in gui",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "richardh",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment] 2019-03-30 09:22
Trac update at `2015/03/10 16:39:05`: 
* **butler** commented:

This while be a lot of work in current framework and unlikely to be achieved in time and while a very nice addition not critical for a release.  Further there is a real question of whether it won't just be easier as part of sasmodels project.  Thus moving to next release for now.  Then we can discuss best course of action


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment] 2019-03-30 09:22
Trac update at `2015/03/22 22:51:48`: **butler** changed workpackage from "SasView Bug Fixing" to "SasView GUI Enhancements"

**Comment by butlerpd** [comment] 2019-03-30 09:22
Trac update at `2015/08/14 20:02:44`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment] 2019-03-30 09:22
Trac update at `2016/03/06 18:24:59`: 
* **butler** commented:

This should be part of the new sasmodels work.  It may be a duplicate of #496 but may be best to think of this as the !SasView GUI interfacing to the new sasmodels properly while ticket #496 refers to building the new sasmodels in a way that makes it easier for the GUI to do this.

Either way it should be part of one of the 6 core tasks for this release so making it blocker.


* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment] 2019-03-30 09:22
Trac update at `2016/03/06 21:03:16`: 
* **butler** commented:

Once all models are converted, suggest Richard look at the order and make sure it makes sense from a user perspective?


* **butler** changed owner from "" to "richardh"
* **butler** changed status from "new" to "assigned"

**Comment by gonzalezma** [comment] 2019-03-30 09:22
Trac update at `2016/03/18 12:09:46`: **gonzalezm** commented:

Solved for single models only.

**Comment by ajj** [comment] 2019-03-30 09:22
Trac update at `2016/03/20 11:46:32`: 
* **ajj** commented:

Miguel has fixed this for single models from sasmodels  i.e. not easy sum/multi.

Closing this as "good enough for 4.0" and will open lower priority tickets for sum/multi and user provided models.


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"

**Closed** 2019-03-30 09:22 UTC
Labels: Migrated from Trac, SasView GUI Enhancements, blocker, enhancement
