### ISSUE TITLE
Project loads and computes but fitting throws an error

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2751] opened 2024-01-19 16:43 UTC
**Describe the bug**
Opening a json project file loads the data and populates the fit page correctly, and the model can be computed. But when you try and fit the model nothing happens and the following errors are thrown:

```
16:28:04 - ERROR: Fitting failed: Traceback (most recent call last):
  File "sas\qtgui\Perspectives\Fitting\FitThread.py", line 79, in compute
  File "sas\qtgui\Perspectives\Fitting\FitThread.py", line 19, in map_apply
  File "sas\qtgui\Perspectives\Fitting\FitThread.py", line 16, in map_getattr
  File "sas\sascalc\fit\BumpsFitting.py", line 291, in fit
AssertionError
16:28:04 - ERROR:  
 === Steps: 1 of 200  chisq: nan  ETA: 0s
  M1.background: 0.00216    |       M1.charge: 68.2       | M1.radius.width: 0.0976    
 M1.volfraction: 0.00148    |
16:28:04 - ERROR: Traceback (most recent call last):
  File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1839, in fitComplete
IndexError: string index out of range
```

**To Reproduce**
1. Run SasView
2. Open the attached project file
3. Compute/Plot
4. Enable some parameters and Fit

**Expected behavior**
Fitting should progress.

**SasView version (please complete the following information):**
Present in at least 5.0.5 & 5.0.6

**Operating system (please complete the following information):**
Present at least in W10/x64

**Additional context**
The project file was submitted by User KelvinW to help@sasview.org on 18/01/2024.

[HCHK.zip](https://github.com/SasView/sasview/files/13991845/HCHK.zip)

**Comment by rozyczko** [comment] 2024-01-19 17:25
Loading the project from the attached file indeed breaks fitting.
However, if I send the data to a new tab, replicate all the parameters as they are in the project's tab and save the project, the subsequent reload works just fine with fitting.
There might've been a problem with that json? 
I'll look a bit deeper but this doesn't seem to be a general issue (hopefully)

**Comment by rozyczko** [comment] 2024-01-19 17:49
Some of the data stored in HCHK.json contains NaNs. Copying those sections to the "good" json causes similar fitting issues. Likely something got broken during the original calculation and the resulting NaNs got serialized, breaking the json...
Not sure what can be done, let's see if we can guard against reading in non-values

**Comment by wpotrzebowski** [comment] 2024-08-19 11:32
We need to check if this is still the case

**Comment by krzywon** [comment] 2024-08-19 21:53
I tested loading the file attached to this ticket with the latest release branch. I am unable to reproduce the error. I will also try my Mac at some point.

**Comment by wpotrzebowski** [comment] 2024-08-20 07:36
Tested on Mac. The issue seems to be resolved, so I am closing it.

**Closed by wpotrzebowski** 2024-08-20 07:36 UTC
Labels: Defect, Loading and Saving, Fitting Perspective, SasView 6.0.0
