### ISSUE TITLE
Integration of sasmodels documentation with SasView (Trac #318)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#453] opened 2019-03-30 08:40 UTC
oops - closed wrong ticket

Migrated from http://trac.sasview.org/ticket/318
```json
{
    "status": "closed",
    "changetime": "2016-03-24T12:01:54",
    "_ts": "2016-03-24 12:01:54.388402+00:00",
    "description": "oops - closed wrong ticket",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2015-02-14T11:09:36",
    "component": "SasView",
    "summary": "Integration of sasmodels documentation with SasView",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "smk78",
    "type": "task"
}
```

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2015/02/15 16:03:28`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2015/02/18 22:58:14`: 
* **butler** commented:

I think all the GUI access to docs has been changed to point to new docs


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2015/02/18 23:29:31`: 
* **butler** changed description from "" to "oops - closed wrong ticket"
* **butler** changed resolution from "fixed" to ""
* **butler** changed status from "closed" to "reopened"

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2015/02/19 22:54:45`: 
* **butler** commented:

Sasmodels is now moving to release + 1 (basically 4.0)


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2015/08/14 20:06:55`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2016/03/06 18:29:04`: 
* **butler** commented:

clearly part of core task "integrating sasmodels into !SasView."  Therefore moving to blocker


* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2016/03/08 03:14:53`: **butler** changed status from "reopened" to "accepted"

**Comment by ajj** [comment] 2019-03-30 09:19
Trac update at `2016/03/20 12:01:06`: 
* **ajj** changed owner from "butler" to "smk78"
* **ajj** changed status from "accepted" to "assigned"

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/20 12:22:29`: **smk78** commented:

20/03/2016 10:45 GMT

SASMODELS documentation now builds without any errors.

Running Sphinx v1.3.1
making output directory...
C:\Code\sasmodels\doc
C:\Code\sasmodels\doc\_extensions
C:\Code\sasmodels

C:\Anaconda2\python27.zip
C:\Anaconda2\DLLs
C:\Anaconda2\lib
C:\Anaconda2\lib\plat-win
C:\Anaconda2\lib\lib-tk
C:\Anaconda2
C:\Anaconda2\Library\bin
c:\anaconda2\lib\site-packages\sphinx-1.3.1-py2.7.egg
c:\anaconda2\lib\site-packages\setuptools-18.4-py2.7.egg
C:\Anaconda2\lib\site-packages
C:\Anaconda2\lib\site-packages\PIL
C:\Anaconda2\lib\site-packages\cryptography-1.0.2-py2.7-win32.egg
C:\Anaconda2\lib\site-packages\win32
C:\Anaconda2\lib\site-packages\win32\lib
C:\Anaconda2\lib\site-packages\Pythonwin
C:\Anaconda2\lib\site-packages\wx-3.0-msw
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 102 source files that are out of date
updating environment: 102 added, 0 changed, 0 removed
reading sources... [100%] ref/refs
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] ref/refs
generating indices... genindex py-modindex
writing additional pages... search
copying images... [100%] model\img/fractal_core_shell_autogenfig.png           ls_autogenfig.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
ECHO is off.
"Build finished. The HTML pages are in _build/html."

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/20 12:41:18`: **smk78** commented:

NOTE: to build the all-in-one pdf you need to have TeX installed (to get pdflatex)!

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/20 17:38:24`: **smk78** commented:

Integrated Sasmodels and !SasView documentation is now building by:
- ''first'' building the Sasmodels documentation (to allow genmodel/gentoc to trawl all the Sasmodels .py files and extract the doc strings into .rst files);
- ''then'' copying those .rst files (and associated image files) to the !SasView /doc folder;
- ''then'' building the !SasView documentation.
Ultimately the first two steps should be replaced by a modified genmodel/gentoc procedure within !SasView. Also see #677.
The !SasView 3.x.x documentation (.rst & images) has been moved to /olddocs subfolders to make way for the new !SasView 4.x.x (ie, Sasmodels) documentation.

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/20 17:43:17`: **smk78** commented:

- The documentation for 3.x.x and 4.x.x are both available from the User Documentation help pages.
- Some 'tidying up' of the User Documentaton tocs has also taken place.
- The 'version' string of the documentation has been changed to 4.0.0-alpha.
- **A way has been found to link the tutorial pdf from the documentation!!!**

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/21 13:36:29`: **smk78** commented:

build_sphinx is now updated with an on-the-fly path replacement for the sasmodels tocs generated by gentoc. This means models can be added/removed, and their names changed, IN SASMODELS with impunity and the integrated docs build will handle the changes without manual intervention.

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/21 19:56:32`: **smk78** commented:

Following today's shenanigans the integrated docs build is now working again!

All dependency on the sasview\src\sas\models folder has been removed and it has been deleted.

The sasmodels docs alone continue to build without errors.

The integrated docs however are throwing 5 issues:

1)
C:\Code\sasview-local-trunk\build\lib.win32-2.7\sas\sascalc\calculator\BaseComponent.py:docstring of sas.sascalc.calculator.BaseComponent.BaseComponent.evalDistribution:14: WARNING: Literal block ends without a blank line; unexpected unindent.

2)
C:\Code\sasview-local-trunk\build\lib.win32-2.7\sas\sascalc\calculator\BaseComponent.py:docstring of sas.sascalc.calculator.BaseComponent.BaseComponent.evalDistribution:31: WARNING: Literal block ends without a blank line; unexpected unindent.

3)
C:\Code\sasview-local-trunk\build\lib.win32-2.7\sas\sasgui\guiframe\data_processor.py:docstring of sas.sasgui.guiframe.data_processor:14: ERROR: Unexpected indentation.

4)
C:\Code\sasview-local-trunk\docs\sphinx-docs\source\dev\api\sas.sasview.rst:116: WARNING: autodoc: failed to import module u'sas.sasview.setup_exe'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\Sphinx-1.3.1-py2.7.egg\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "C:\Code\sasview-local-trunk\build\lib.win32-2.7\sas\sasview\setup_exe.py", line 21, in <module>
    raise !RuntimeError("Must run setup_exe from the sasview directory")
!RuntimeError: Must run setup_exe from the sasview directory

5)
C:\Code\sasview-local-trunk\docs\sphinx-docs\source\dev\api\sas.sasview.rst:124: WARNING: autodoc: failed to import module u'sas.sasview.setup_mac'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\Sphinx-1.3.1-py2.7.egg\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "C:\Code\sasview-local-trunk\build\lib.win32-2.7\sas\sasview\setup_mac.py", line 43, in <module>
    import sas.models as models
!ImportError: No module named models

I haven't thus far been able to see where they are coming from. Help welcome!

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2016/03/22 15:35:02`: **butler** commented:

First items I think are fixed (Note directive now works properly).  The last two I don't think get "fixed" they are what they say -- they don't work unless running from the exe evironment.  They should probably be excluded from the docs build? At any rate they do not seem to affect the documentation output in any way.

data_processor on the other hand is the one py file with a doc string containing a reference to a figure which is not properly being sucked in.  It was in the old docs so probably a path issue of some kind -- still to work on, but the docs build (just a broken image icon in the dev docs at the point where that figure should be.

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2016/03/22 19:24:18`: **butler** commented:

data_processor now fixed... at least for loading figure.  SMK should check again.

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/22 21:00:38`: **smk78** commented:

19:30 GMT
Have just checked sasmodels and integrated sasview docs build at PaulB's request. Used Sphinx 1.3.6.

Issues 4) & 5) above still exist.

Just one (irritating) undefined label warning to mag_help in core_multi_shell is left. I ''think'' it is because mag_help is in a different folder when the docs get built so the :ref: can't find it but I haven't thus far found a path string that includes it...

**But** I have also just noticed that fitting_help, for example, (see the batch fit section) is not finding:

 - gen_gui_help.bmp
 - mag_vector.bmp 
 - mag_vector.bmp     
 - new_model.bmp     
 - plot_button.bmp    
 - view_button.bmp   

when the page renders.

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2016/03/23 01:13:08`: **butler** commented:

actually the bmp files are found no problem.  The issue is that somewhere along the way those files became corrupt - Loading with a simple image viewer gives the message that they are corrupt.  Need to find the original files ... probably can find on github at some previous revision.

ref I think is not done right ... but need to look into that more.

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/23 15:29:18`: **smk78** commented:

Have committed 'working' versions of the .bmp files. Images in fitting_help now render ok.

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/23 15:35:48`: **smk78** commented:

With the exception of the setup_exe and setup_mac warnings, and the problematic undefined label, (see above) the integrated docs seem fine now.

**Comment by butlerpd** [comment] 2019-03-30 09:19
Trac update at `2016/03/24 11:03:02`: **butler** commented:

broken link is now fixed ... temporarily -- sasmodels cannot be linking to !SasView documentation in the long run since !SasView depends on sasmodels not the other way round and others may also depend on sasmodels.  Have created ticket to that effect for next release+1.  Also have added a ticket to cleanu up a bunch of stuff in build_sphinx.py.  The exe and mac scrapes should be fixed as part of that (i.e. we should not be scraping those files!).

I think this ticket can now be closed.

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/24 12:00:27`: **smk78** commented:

Sasmodels build warning has now changed to:

E:\SasViewDevelopment\sasmodels\doc\model\core_multi_shell.rst:123: WARNING: unknown document: ../sasgui/perspectives/fitting/mag_help

but the integrated build now resolves this.

I am closing the ticket.

**Comment by smk78** [comment] 2019-03-30 09:19
Trac update at `2016/03/24 12:01:54`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"

**Closed** 2019-03-30 09:19 UTC
Labels: Migrated from Trac, SasView Documentation, blocker, task
