### ISSUE TITLE
ESS_GUI: Bit too easy to close a Fit Page by mistake on small screens

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1651] opened 2020-08-05 08:19 UTC
User MartinH comments on 5.0.3:

_One relatively minor point of feedback is that when clicking between different fit pages when doing a constrained fit (e.g. the ones representing the different contrasts - to see what parameters have fitted to) it's very easy to click the "X" that closes the page. I've done this carelessly now several times and obviously that means pretty-much starting again (at least for the one that is closed). I realise that I should be able to be less clumsy(!) but could a "do you really want to close this window" be brought in perhaps to prevent that? Just a suggestion!_

Here's the view on my laptop screen:
![image](https://user-images.githubusercontent.com/10938679/89388850-803ff800-d6fc-11ea-8358-ba7673d4a05b.png)

I can kind of see his point.

**Comment by krzywon** [comment] 2020-08-05 10:25
This might be a duplicate of #1166 - warning users when closing fit pages. More people saying the same thing means we should probably bump the priority up on this.

**Comment by smk78** [comment] 2020-08-05 13:36
Dang you @krzywon ! And I even searched the issues list to see if it was already ticketed! (Though evidently not well enough)

I note though that https://github.com/SasView/sasview/issues/1166 is directed at 4.x and labelled Won't Fix. Since we cannot at present assign tickets to both the 4.x and 5.x branches, I suggest we leave this one open for now.

**Comment by pkienzle** [comment] 2020-08-05 14:32
Rather than popping up a dialog on close in case it is an accidental close, I suggest making it harder to select close in the first place.  Can we remove the "close" option from the tab and instead make it a menu choice? A button within the panel is a better option if deleting a fit is a common operation. Someone who uses sasview for fitting data will have to make that call.

**Comment by rozyczko** [comment] 2020-08-05 20:49
Generally any operation which involves losing data should be hiding behind a confirmation window.
Closing the tab is of course removing user data.
One option is to temporarily retain the data and allow some sort of "show recently closed tab", similar to Ctrl-Shift-T in most internet browsers.
The confirmation window can be further extended by asking users if closing tabs should show warn them every time, again similarly to what other apps do in similar situations.

**Comment by pkienzle** [comment] 2020-08-05 21:57
Clicking "Fit" also loses data, as does selecting a different model

**Comment by rozyczko** [comment] 2020-08-18 09:34
The widget in the screenshot looks hideous! I've never seen font size making this widget so unusable. Is this something more common that should be looked at?

**Comment by smk78** [comment] 2020-08-18 09:44
It would seem to depend on one's screen resolution, @rozyczko . To be fair, at higher res it is better.

**Comment by rozyczko** [comment] 2020-08-18 09:58
Oof.. then this has to be addressed. #1662

**Comment by lucas-wilkins** [comment] 2022-10-30 20:40
Closing as addressed in #1662 and also because there is now a scale factor setting

**Closed by lucas-wilkins** 2022-10-30 20:40 UTC
Labels: Enhancement, SasView GUI Enhancements
