### ISSUE TITLE
Recalculate P(Q) and S(Q) components on model update. (Trac #741)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#857] opened 2019-03-30 08:47 UTC
If the new theory S(Q) is appended to a plot, it does not change when performing fits until you append again.

Can we have it to auto-update please, likewise P(Q) etc.

Migrated from http://trac.sasview.org/ticket/741
```json
{
    "status": "closed",
    "changetime": "2017-09-13T14:22:41",
    "_ts": "2017-09-13 14:22:41.352008+00:00",
    "description": "If the new theory S(Q) is appended to a plot, it does not change when performing fits until you append again.\n\nCan we have it to auto-update please, likewise P(Q) etc.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-08T19:31:31",
    "component": "SasView",
    "summary": "Recalculate P(Q) and S(Q) components on model update.",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "lewis",
    "type": "defect"
}
```

**Comment by butlerpd** [comment] 2019-03-30 09:55
Trac update at `2016/10/27 16:03:57`: 
* **butler** commented:

As discussed at Tuesday's meetig (Oct 25), actually this is a function of the way !GuiFrame works: All theory "data" behaves this same way.  Mainly the underlying theory data will change and the plot that is generated at the same time as that data is updated BUT ... if one goes the other way by sneding such a "data" to "New Plot" from the data explorer it is done via a copy of the data.  That copy does not change and is therefore there is nothing to update.  I believe the use of copy was because trying to make the plot just another view onto the same data (which is what it should be) caused a lot of other problems.  

With the 5.0 GUI refactoring this is probably best left for that release and added to the tickets for the ESS branch to be considering in the refactor)


* **butler** changed milestone from "SasView 4.1.0" to "SasView 5.0.0"

**Comment by butlerpd** [comment] 2019-03-30 09:55
Trac update at `2016/10/27 16:04:23`: 
* **butler** changed owner from "mathieu" to "piotr"
* **butler** changed status from "new" to "assigned"

**Comment by smk78** [comment] 2019-03-30 09:55
Trac update at `2017/02/20 14:37:29`: **smk78** commented:

ESS Jenkins Win7 Build 640:

If you are fitting:
The first time you plot or append the P(Q) & S(Q) theories you get something sensible. But thereafter, no matter what you do to change P(Q) or S(Q), whether you select append or new plot, you only get the same (original) traces for P(Q) or S(Q). The combined MODEL trace changes, so P(Q) and S(Q) are being recalculated, but the individual component THEORIES are not being updated.

If you are simulating (computing); ie, you ONLY have THEORIES, no data:
You cannot display P(Q) or S(Q) at all. All you get is the error

Plotting Error: Plottable.View: Given y and x are not of the same length

**Comment by ajj** [comment] 2019-03-30 09:55
Trac update at `2017/03/27 11:37:14`: 
* **ajj** commented:

Plottting error is gone, but the separated components are not updated (#987 was duplicate of this ticket).

Why was this not a blocker for 4.1? The plotting of P(Q) and S(Q) was a requirement for this release but does not work properly.

If the items were updated then the plots will update.


* **ajj** changed milestone from "SasView 5.0.0" to "SasView 4.1.0"
* **ajj** changed owner from "piotr" to "mathieu"
* **ajj** changed priority from "major" to "blocker"
* **ajj** changed summary from "can we auto-update S(Q) etc if appended to a plot?" to "Recalculate P(Q) and S(Q) components on model update."

**Comment by ajj** [comment] 2019-03-30 09:55
Trac update at `2017/03/30 14:10:15`: 
* **ajj** changed resolution from "fixed" to ""
* **ajj** changed status from "closed" to "reopened"

**Comment by ajj** [comment] 2019-03-30 09:55
Trac update at `2017/03/30 14:10:24`: **ajj** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by butlerpd** [comment] 2019-03-30 09:55
Trac update at `2017/04/11 13:02:20`: **butler** commented:

In changeset 24b382118c3145d493e1f76e2b308e6aa6f0759c:

```text
#!CommitTicketReference repository="sasview" revision="24b382118c3145d493e1f76e2b308e6aa6f0759c"
re-enable calculation/separation of P & S in SasView (appearing under
the model they fit or in theory as appropriate) addresses #857
```

**Comment by butlerpd** [comment] 2019-03-30 09:55
Trac update at `2017/07/12 01:25:58`: 
* **butler** changed owner from "mathieu" to "butler"
* **butler** changed status from "reopened" to "assigned"

**Comment by butlerpd** [comment] 2019-03-30 09:55
Trac update at `2017/08/27 04:11:23`: 
* **butler** commented:

Lewis has taken this over so changing assignment


* **butler** changed owner from "butler" to "lewis"

**Closed** 2019-03-30 09:55 UTC
Labels: Migrated from Trac, SasView Bug Fixing, blocker, defect
