### ISSUE TITLE
set theory and data to same vmin/vmax when plotting 2D data (Trac #846)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#937] opened 2019-03-30 08:49 UTC
It will be much easier to see the difference between 2D data to 2D theory if they use the same range for the colour bar.

Migrated from http://trac.sasview.org/ticket/846
```json
{
    "status": "new",
    "changetime": "2017-10-23T15:29:50",
    "_ts": "2017-10-23 15:29:50.291582+00:00",
    "description": "It will be much easier to see the difference between 2D data to 2D theory if they use the same range for the colour bar.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView GUI Enhancements",
    "time": "2017-02-07T17:06:56",
    "component": "SasView",
    "summary": "set theory and data to same vmin/vmax when plotting 2D data",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by rozyczko** [comment] 2019-03-30 10:04
Trac update at `2017/07/13 11:45:30`: **piotr** commented:

Not sure I can reproduce that.
- create a 2D theory
- freeze it as data
- plot the 2D theory and 2D data
- both have the same colour range, being the same data

Unless you want to have the same range for different data sets?

**Comment by butlerpd** [comment] 2019-03-30 10:04
Trac update at `2017/10/23 15:28:41`: **butler** changed milestone from "SasView 4.2.0" to "SasView 5.0.0"

**Comment by butlerpd** [comment] 2019-03-30 10:04
Trac update at `2017/10/23 15:29:50`: **butler** commented:

This may not be an issue in the new GUI? if not we can close.

**Comment by rozyczko** [comment] 2019-07-26 08:56
Unable to reproduce in 5.0. Closing.

**Closed by rozyczko** 2019-07-26 08:56 UTC
Labels: Migrated from Trac, SasView GUI Enhancements, defect, major
